# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jons games
tagline:          Just some things, made by a guy.
description:      Game developer in London, UK. Currently making extensive use of <a href="https://unity3d.com/" target="_blank">Unity.</a>
url:              http://jonsgames.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

projects:
- name: Relay
  image: /public/images/relay.png
  page: /projects/relay
- name: DROLF
  image: /public/images/drolf.png
  page: /projects/drolf
- name: bubble trubble
  image: /public/images/bubbletrubble.png
  page: /projects/bubbletrubble
- name: SNOMAN
  image: /public/images/snoman.png
  page: /projects/snoman
- name: Honey Giants
  image: /public/images/honeygiants.png
  page: /projects/honeygiants
- name: Mesh Tools
  image: /public/images/meshtools.png
  page: /projects/meshtools
- name: Rugged Rovers
  image: /public/images/ruggedrovers.png
  page: /projects/ruggedrovers
- name: Jazz Manatee
  image: /public/images/jazzmanatee.png
  page: /projects/jazzmanatee
- name: Scaffolding
  image: /public/images/scaffolding.png
  page: /projects/scaffolding
- name: Love Conncetion
  image: /public/images/loveconnection.png
  page: /projects/loveconnection
- name: Story Cards
  image: /public/images/storycards.png
  page: /projects/storycards
- name: TyrAnt
  image: /public/images/tyrant.png
  page: /projects/tyrant
- name: Lets click and makeup
  image: /public/images/letsclickandmakeup.png
  page: /projects/letsclickandmakeup
- name: Atmosfeast
  image: /public/images/atmosfeast.png
  page: /projects/atmosfeast
- name: Spaced Out
  image: /public/images/spacedout.png
  page: /projects/spacedout
